### ISSUE TITLE
Добавление префикса к компонентам

### ISSUE THREAD

**Issue by ExEr7um** [Pacific-Agency/nuxt-utils#92]
Чтобы не было проблем с тем, что созданные компоненты называются одинаково с уже имеющимися, необходимо добавить им префикс.

### Варианты
- `NU`, например `NUMapWidget`
- `NuxtUtils`, например `NuxtUtilsMapWidget`
- `Utils`, например `UtilsMapWidget`

**Comment by ExEr7um** [comment]
@Iskait что считаешь?

Мне кажется 2 или 3 лучше выглядят.

**Comment by Iskait** [comment]
А?
